### ISSUE TITLE
ValueError: SISSOJob requires the SISSO executable to be in the path.

### ISSUE THREAD

**Issue by KirbyBroderick** [Matgenix/pysisso#14]
Hi, I'm just beginning to use this package, and I can't seem to get the example working. 

System: NVIDIA HPC SDK 20.11
CUDA 11.0 Ubuntu 20.04

Steps to reproduce:

1. Install poetry: `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -`
2. Add poetry to path `export PATH="$HOME/.poetry/bin:$PATH"`
3. Clone pysisso:`git clone git@github.com:Matgenix/pysisso.git`
4. Install pysisso: `cd pysisso ** poetry install`
5. Open poetry: `poetry shell`
6. Run example: `python examples_usage/basic/01_regression/cubic_function.py`

Stack trace:

> Traceback (most recent call last):
  File "examples_usage/basic/01_regression/cubic_function.py", line 59, in <module>
    sisso_regressor.fit(X, y)
  File "/home/jovyan/pysisso/pysisso/sklearn.py", line 271, in fit
    c.run()
  File "/home/jovyan/.cache/pypoetry/virtualenvs/pysisso-zaPbc9Aa-py3.7/lib/python3.7/site-packages/custodian/custodian.py", line 372, in run
    self._run_job(job_n, job)
  File "/home/jovyan/.cache/pypoetry/virtualenvs/pysisso-zaPbc9Aa-py3.7/lib/python3.7/site-packages/custodian/custodian.py", line 450, in _run_job
    p = job.run()
  File "/home/jovyan/pysisso/pysisso/jobs.py", line 58, in run
    self.SISSO_exe
ValueError: SISSOJob requires the SISSO executable to be in the path.
Default executable name is "SISSO" and you provided "SISSO".
Download the SISSO code at https://github.com/rouyang2017/SISSO and compile the executable or fix the name of your executable.

Any idea what could be going wrong?

**Comment by davidwaroquiers** [comment]
Hi,

Thank you for your message. Do you indeed have SISSO (https://github.com/rouyang2017/SISSO) installed ? pysisso is designed as a wrapper to SISSO and it needs to have the SISSO executable in your PATH. Could you issue "which SISSO" in your terminal and see if it finds SISSO.

**Comment by KirbyBroderick** [comment]
That was it, thanks!

**Comment by sky8fall** [comment]
sorry, there are some stupid questions.
1. This code should run in shell/ Linux because SISSO cannot compile to.EXE is on Windows, right? 
2. I run this example on shell connect to the server, python 3.8 .   _python examples_usage/basic/01_regression/cubic_function.py_
3. **in error.file**
Job return code is 143. Terminating...
Traceback (most recent call last):
  File "./cubic_function.py", line 59, in <module>
    sisso_regressor.fit(X, y)
  File "/home/scms/sk/anaconda3/lib/python3.8/site-packages/pysisso/sklearn.py", line 271, in fit
    c.run()
  File "/home/scms/sk/anaconda3/lib/python3.8/site-packages/custodian/custodian.py", line 372, in run
    self._run_job(job_n, job)
  File "/home/scms/sk/anaconda3/lib/python3.8/site-packages/custodian/custodian.py", line 510, in _run_job
    raise ReturnCodeError(s, True)
custodian.custodian.ReturnCodeError: Job return code is 143. Terminating...
**in log.file**
Directory is /home/scms/sk/discoverEq/pysisso-master/examples_usage/basic/01_regression
This job runs on the following nodes:
cnode001
This job has allocated 40 cpu cores.

is there anything wrong..   i try to google and figure out,but no results

**Comment by sky8fall** [comment]
and the SISSO_dir is created.
**SISSO.log** is empty
**SISSO.err** shows
 Abort(2140047) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(703)........:
MPID_Init(958)...............:
MPIDI_OFI_mpi_init_hook(1334):
MPIDU_bc_table_create(444)...:

**custodian.json** shows
[
    {
        "job": {
            "@module": "pysisso.jobs",
            "@class": "SISSOJob",
            "@version": null,
            "SISSO_exe": "SISSO",
            "nprocs": 1,
            "stdout_file": "SISSO.log",
            "stderr_file": "SISSO.err"
        },
        "corrections": [],
        "handler": null,
        "validator": null,
        "max_errors": false,
        "max_errors_per_job": false,
        "max_errors_per_handler": false,
        "nonzero_return_code": true
    }
]
~

**Comment by davidwaroquiers** [comment]
Hi,

Could you try to just run SISSO. It seems to be an issue with SISSO not with pysisso.

**Comment by sky8fall** [comment]
if I run SISSO alone, I can get the normal result. （“ it needs to have the SISSO executable in your PATH”）Is it my path error? I put SISSO program at ~/anaconda3/bin/SISSO
